export const PAYOUT_TASK_STATUSES = {
  PENDING_PAYMENT_INFORMATION: 'PENDING_PAYMENT_INFORMATION',
  PENDING_TO_PAY: 'PENDING_TO_PAY',
  PAID: 'PAID',
  ARCHIVED: 'ARCHIVED',
} as const;

export type PayoutTaskStatus =
  (typeof PAYOUT_TASK_STATUSES)[keyof typeof PAYOUT_TASK_STATUSES];
